### ISSUE TITLE
Ask about the resource to replicate the paper

### ISSUE THREAD

**Issue by pavaris-pm** [bookpanda/WanchanBERTa-Thai-Grammarly#1]
Hope this issue finds you well! I'm very impressed and interested in your work for building a word correction model. 

Since the upcoming of `PhayaThaiBERT`, a current state-of-the-art Thai encoder-based model , it brings an impressive performance on many thai benchmark. According to that, i've added new features into PyThaiNLP library where the details of it are in this [PR #873](https://github.com/PyThaiNLP/pythainlp/pull/873), you can take a quick look at it krub.

Moreover, i have an idea to replicate your word correction model but change the architecture to be `PhayaThaiBERT` instead of `WangchanBERTa`. Then, i will add it into PyThaiNLP library krub. Note that all credits will be given to you as an author of this paper (i will make a co-author commit so that you will get a credit from this features as well).   Would you agree with that ?

In order to replicate that, i want to ask you that did you have an available dataset to be used instantly or any notebook that can be used to replicate an entire pipeline starting from forming a word correction dataset and also a model building. I've started from this [notebook]( https://github.com/bookpanda/Two-stage-Thai-Misspelling-Correction-Based-on-Pre-trained-Language-Models/blob/main/tpth/data_tpth.ipynb) and do it as follows, but what i've found is an error at the middle of the notebook krub. Can you please give me a complete notebook that can construct the dataset to train the word correction model up into an applicable one krub.

**Comment by bookpanda** [comment]
Hi, it seems that the tokenizer couldn't be initialized, right? I've push some fixes now. Sorry for the messy code, there are some blocks that may seem out-of-nowhere and cannot be run, please ignore them (pre-college me didn't know anything about clean code). This is the [VISTEC-TP-TH-2021.csv](https://github.com/mrpeerat/OSKut/tree/main/VISTEC-TP-TH-2021) raw dataset.

Please feel free to modify any part of the code that seems odd since it was written when I just started coding in Python and many things were total ad-hoc.

**Comment by pavaris-pm** [comment]
> Hi, it seems that the tokenizer couldn't be initialized, right? I've push some fixes now. Sorry for the messy code, there are some blocks that may seem out-of-nowhere and cannot be run, please ignore them (pre-college me didn't know anything about clean code). This is the [VISTEC-TP-TH-2021.csv](https://github.com/mrpeerat/OSKut/tree/main/VISTEC-TP-TH-2021) raw dataset.
> 
> 
> 
> Please feel free to modify any part of the code that seems odd since it was written when I just started coding in Python and many things were total ad-hoc.

Thanks for your quick reply. It was very impressive when pre-college student bringing up a new proposing method of word correction model to Thai NLP. If there has any part of code that need to be refactored, I will help fixing it and made a new PR krub.

Thanks again for your excellent work. Keep up with your new ideas!

**Comment by bookpanda** [comment]
It was a project in the [AI Builders](https://github.com/ai-builders) program, I couldn't thank my mentor and professor enough for their guidance. Thank you very much, have a nice day.
